Repository uswds/uswds, pull requests merged in 2019-12, with the labels that each got.

#3252 USWDS - styles.scss Imports: Remove duplicate layout-grid import.
  src/stylesheets/theme/styles.scss
Labels: improves: correctness, type: bug

#3253 Prevent subcomponent type styles from overriding the primary component
  package-lock.json
  src/stylesheets/components/_banner.scss
  src/stylesheets/components/_footer.scss
  src/stylesheets/components/_navigation.scss
Labels: affects: banner, affects: footer, affects: nav, changes: appearance, improves: correctness, type: bug

#3259 Issue-3256: Prevent focus outline from being overridden.
  src/stylesheets/elements/_buttons.scss
Labels: affects: button, improves: continuity, improves: correctness, type: bug

#3258 Allow non-token values in theme color settings
  src/stylesheets/core/_functions.scss
  src/stylesheets/core/_variables.scss
  src/stylesheets/settings/_settings-color.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/settings/_settings-general.scss
  src/stylesheets/settings/_settings-spacing.scss
  src/stylesheets/settings/_settings-typography.scss
  src/stylesheets/settings/_settings-utilities.scss
  src/stylesheets/theme/_uswds-theme-color.scss
  src/stylesheets/theme/_uswds-theme-components.scss
  src/stylesheets/theme/_uswds-theme-general.scss
  src/stylesheets/theme/_uswds-theme-spacing.scss
  src/stylesheets/theme/_uswds-theme-utilities.scss
Labels: affects: colors, improves: continuity, type: enhancement

#3260 Publish v1 branch with v1 tag
  .circleci/config.yml
Labels: affects: ci, improves: correctness, improves: trust, type: enhancement, version: 1.x

#3265 Update dependencies
  package-lock.json
  package.json
Labels: changes: dependencies, improves: security, improves: stability, topic: dependencies

#3261 Promote better deprecation communication and compatibility
  src/stylesheets/core/_deprecated.scss
  src/stylesheets/core/_notifications.scss
  src/stylesheets/packages/_required.scss
  src/stylesheets/settings/_settings-general.scss
  src/stylesheets/theme/_uswds-theme-general.scss
Labels: affects: compiling, improves: continuity, improves: documentation, improves: stability, type: enhancement

#3266 Update references to 2.4.0
  README.md
  src/stylesheets/settings/_settings-color.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/settings/_settings-general.scss
  src/stylesheets/settings/_settings-spacing.scss
  src/stylesheets/settings/_settings-typography.scss
  src/stylesheets/settings/_settings-utilities.scss
  src/stylesheets/theme/_uswds-theme-color.scss
  src/stylesheets/theme/_uswds-theme-components.scss
  src/stylesheets/theme/_uswds-theme-general.scss
  src/stylesheets/theme/_uswds-theme-spacing.scss
  src/stylesheets/theme/_uswds-theme-typography.scss
  src/stylesheets/theme/_uswds-theme-utilities.scss
Labels: improves: correctness, improves: documentation

#3267 Improve messaging about notification in notification
  src/stylesheets/core/_notifications.scss
Labels: improves: documentation

#3268 Release 2.4.0
  README.md
  docs/WHO_IS_USING_USWDS.md
  fractal.js
  package-lock.json
  package.json
  src/stylesheets/components/_banner.scss
  src/stylesheets/components/_footer.scss
  src/stylesheets/components/_navigation.scss
  src/stylesheets/core/_deprecated.scss
  src/stylesheets/core/_functions.scss
  src/stylesheets/core/_notifications.scss
  src/stylesheets/core/_variables.scss
  src/stylesheets/core/placeholders/_table.scss
  src/stylesheets/elements/_buttons.scss
  src/stylesheets/packages/_required.scss
  src/stylesheets/settings/_settings-color.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/settings/_settings-general.scss
  src/stylesheets/settings/_settings-spacing.scss
  src/stylesheets/settings/_settings-typography.scss
  src/stylesheets/settings/_settings-utilities.scss
  src/stylesheets/theme/_uswds-theme-color.scss
  src/stylesheets/theme/_uswds-theme-components.scss
  src/stylesheets/theme/_uswds-theme-general.scss
  src/stylesheets/theme/_uswds-theme-spacing.scss
  src/stylesheets/theme/_uswds-theme-typography.scss
  src/stylesheets/theme/_uswds-theme-utilities.scss
  src/stylesheets/theme/styles.scss
Labels: affects: banner, affects: colors, affects: compiling, affects: footer, affects: table, improves: continuity, improves: correctness, improves: documentation, improves: stability
