Repository uswds/uswds, pull requests merged in 2020-03, with the labels that each got.

#3326 [USWDS] - [gulp sass] Disable forceMediaMerge in CSSO.
  README.md
  config/gulp/sass.js
  package-lock.json
  package.json
  spec/axe-tester.js
Labels: needs: confirmation, needs: feedback, needs: review

#3336 Release 2.5.1
  README.md
  config/gulp/sass.js
  package-lock.json
  package.json
  spec/axe-tester.js
  src/stylesheets/core/_notifications.scss
  src/stylesheets/settings/_settings-color.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/settings/_settings-general.scss
  src/stylesheets/settings/_settings-spacing.scss
  src/stylesheets/settings/_settings-typography.scss
  src/stylesheets/settings/_settings-utilities.scss
  src/stylesheets/theme/_uswds-theme-color.scss
  src/stylesheets/theme/_uswds-theme-components.scss
  src/stylesheets/theme/_uswds-theme-general.scss
  src/stylesheets/theme/_uswds-theme-spacing.scss
  src/stylesheets/theme/_uswds-theme-typography.scss
  src/stylesheets/theme/_uswds-theme-utilities.scss
Labels: affects: compiling

#3343 Synchronize letterspacing values
  src/stylesheets/core/_properties.scss
Labels: improves: correctness

#3327 USWDS - Search: Use consistent search markup.
  src/components/search/search--header.njk
  src/components/search/search.njk
  src/stylesheets/components/_search.scss
Labels: affects: search, needs: feedback

#3375 Use direct link to zip file
  README.md
Labels: improves: correctness
