Repository uswds/uswds, pull requests merged in 2021-03, with the labels that each got.

#4056 Rebuild components to make uswds-site more accessible
  .snyk
  src/components/_uswds-form.njk
  src/components/accordion/accordion.njk
  src/components/alerts/alerts.njk
  src/components/button-groups/button-groups--segmented.njk
  src/components/button-groups/button-groups.njk
  src/components/card/card--flag.njk
  src/components/card/card--standard.njk
  src/components/card/card.config.yml
  src/components/checkbox/checkbox--tile.njk
  src/components/checkbox/checkbox.config.yml
  src/components/checkbox/checkbox.njk
  src/components/checkboxes/checkboxes--tile.njk
  src/components/checkboxes/checkboxes.njk
  src/components/collection/collection--fancy-date.njk
  src/components/collection/collection--media.njk
  src/components/collection/collection--only-headers.njk
  src/components/collection/collection.njk
  src/components/combo-box/combo-box.config.yml
  src/components/date-input/date-input.config.yml
  src/components/date-input/date-input.njk
  src/components/date-picker/date-picker.config.yml
  src/components/date-picker/date-picker.njk
  src/components/date-range-picker/date-range-picker.config.yml
  src/components/date-range-picker/date-range-picker.njk
  src/components/dropdown/dropdown.config.yml
  src/components/dropdown/dropdown.njk
  src/components/file-input/file.njk
  src/components/navigation/sidenav--compare.njk
  src/components/navigation/sidenav.config.yml
  src/components/radio-buttons/radio-buttons--tile.njk
  src/components/radio-buttons/radio-buttons.config.yml
  src/components/radio-buttons/radio-buttons.njk
  src/components/range-input/range-input.njk
  src/components/range-slider/range-slider.config.yml
  src/components/range-slider/range-slider.njk
  src/components/step-indicator/step-indicator.njk
  src/components/tag/tag.config.yml
  src/components/tag/tag.njk
  src/components/text-input/text-input.config.yml
  src/components/text-input/text-input.njk
  src/components/time-picker/time-picker.config.yml
  src/components/time-picker/time-picker.njk
  src/components/type/typesetting--headings.njk
  src/components/type/typesetting--line-length.njk
  src/components/validation/validation.config.yml
  src/components/validation/validation.njk
  src/stylesheets/elements/form-controls/_date-input.scss
  src/stylesheets/elements/form-controls/_date-picker.scss
  src/stylesheets/elements/form-controls/_global.scss
Labels: has related docs pr

#4061 Add white expand icon variant
  src/img/usa-icons-bg/add--white.svg
  src/img/usa-icons-bg/expand_more--white.svg
  src/img/usa-icons-bg/remove--white.svg
Labels: USWDS 2.10.2, affects: icons, enhancement

#3950 Add table sorting
  spec/unit/accordion/accordion.spec.js
  spec/unit/banner/banner.spec.js
  spec/unit/character-count/character-count.spec.js
  spec/unit/character-count/valid-template-multiple-validators.spec.js
  spec/unit/character-count/valid-template-no-maxlength.spec.js
  spec/unit/combo-box/combo-box-change-event.spec.js
  spec/unit/combo-box/combo-box-default-value.spec.js
  spec/unit/combo-box/combo-box-disable-filtering.spec.js
  spec/unit/combo-box/combo-box-disabled.spec.js
  spec/unit/combo-box/combo-box-filter.spec.js
  spec/unit/combo-box/combo-box-placeholder.spec.js
  spec/unit/combo-box/combo-box-subsequent-selection.spec.js
  spec/unit/combo-box/combo-box.spec.js
  spec/unit/combo-box/generateDynamicRegExp.spec.js
  spec/unit/date-picker/date-picker-default-date.spec.js
  spec/unit/date-picker/date-picker-default-value.spec.js
  spec/unit/date-picker/date-picker-disabled.spec.js
  spec/unit/date-picker/date-picker-min-date-max-date.spec.js
  spec/unit/date-picker/date-picker-month-selection.spec.js
  spec/unit/date-picker/date-picker-mousemove.spec.js
  spec/unit/date-picker/date-picker-range-date.spec.js
  spec/unit/date-picker/date-picker-year-selection.spec.js
  spec/unit/date-picker/date-picker.spec.js
  spec/unit/date-picker/invalid-template-no-wrapper.spec.js
  spec/unit/date-range-picker/date-range-picker-min-date-max-date.spec.js
  spec/unit/date-range-picker/date-range-picker.spec.js
  spec/unit/date-range-picker/invalid-template-no-wrapper.spec.js
  spec/unit/file-input/file-input.spec.js
  spec/unit/file-input/single-file-input.spec.js
  spec/unit/footer/footer.spec.js
  spec/unit/navigation/navigation.spec.js
  spec/unit/skipnav/skipnav.spec.js
  spec/unit/table/table.spec.js
  spec/unit/table/template.html
  spec/unit/time-picker/time-picker-regex.spec.js
  spec/unit/time-picker/time-picker.spec.js
  spec/unit/toggle-fields/toggle-field-mask.spec.js
  spec/unit/toggle-fields/toggle-form-input.spec.js
  spec/unit/tooltip/tooltips.spec.js
  spec/unit/utils/behavior.spec.js
  spec/unit/utils/select.spec.js
  spec/unit/validator/validator.spec.js
  src/components/table/table--sortable.config.yml
  src/components/table/table--sortable.njk
  src/components/table/table--stacked.njk
  src/js/components/index.js
  src/js/components/table.js
  src/stylesheets/core/placeholders/_table.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/theme/_uswds-theme-components.scss
Labels: Accelerator, Accelerator: Component

#3981 USWDS - Modal: Create modal component
  spec/unit/modal/modal.spec.js
  spec/unit/modal/template.html
  src/components/modal/modal.config.yml
  src/components/modal/modal.njk
  src/components/test/kitchen-sink.njk
  src/js/components/index.js
  src/js/components/modal.js
  src/js/components/navigation.js
  src/js/utils/focus-trap.js
  src/js/utils/scrollbar-width.js
  src/stylesheets/components/_card.scss
  src/stylesheets/components/_footer.scss
  src/stylesheets/components/_header.scss
  src/stylesheets/components/_modal.scss
  src/stylesheets/core/_variables.scss
  src/stylesheets/packages/_usa-modal.scss
  src/stylesheets/packages/_uswds-components.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/theme/_uswds-theme-components.scss
  src/stylesheets/theme/styles.scss
Labels: Accelerator

#3876 Add icon list component
  src/components/_uswds-content.njk
  src/components/icon-list/icon-list.config.yml
  src/components/icon-list/icon-list.njk
  src/stylesheets/components/_icon-list.scss
  src/stylesheets/core/mixins/_at-media.scss
  src/stylesheets/packages/_usa-icon-list.scss
  src/stylesheets/packages/_uswds-components.scss
  src/stylesheets/settings/_settings-components.scss
  src/stylesheets/theme/_uswds-theme-components.scss
Labels: Accelerator

#3996 Fix link styling in usa-prose
  src/stylesheets/elements/typography/_prose.scss
Labels: USWDS 2.11.0, affects: typography, enhancement, size: minutes
