Repository uswds/uswds, pull requests merged in 2021-05, with the labels that each got.

#4197 Accessibility updates [uswds-site 1227]
  README.md
  SECURITY.md
  package-lock.json
  src/components/banner/banner.config.yml
  src/components/banner/banner.njk
  src/components/breadcrumb/_breadcrumb--metadata.njk
  src/components/breadcrumb/breadcrumb.config.yml
  src/components/breadcrumb/breadcrumb.njk
  src/components/button-groups/button-groups.njk
  src/components/collection/collection--only-headers.njk
  src/components/footer/footer--big.njk
  src/components/footer/footer--slim.njk
  src/components/identifier/identifier.config.yml
  src/components/layouts/error-inner.njk
  src/components/layouts/landing-inner.njk
  src/components/navigation/sidenav.config.yml
  src/components/navigation/sidenav.njk
  src/components/site-alert/site-alert.config.yml
  src/components/site-alert/site-alert.njk
  src/components/summary-box/summary-box.njk
  src/components/table/table--scrollable.njk
  src/components/type/lists.njk
  src/components/type/typesetting.njk
Labels: needs: additional change to website

#4179 USWDS - Process list: Create package.
  src/stylesheets/packages/_usa-process-list.scss
Labels: bug

#4134 USWDS - Deps: Remove gulp-sass from develop branch.
  config/gulp/sass.js
  gulpfile.js
  package-lock.json
  package.json
Labels: USWDS 2.12.0

#4183 Update `success-dark` to vivid variant
  src/stylesheets/settings/_settings-color.scss
  src/stylesheets/theme/_uswds-theme-color.scss
Labels: topic: color
