Repository uswds/uswds, pull requests merged in 2024-10, with the labels that each got.

#5970 USWDS - Pagination: Updated text-decoration value to better show pagination links
  packages/usa-pagination/src/styles/_usa-pagination.scss
Labels: A11Y Audit Findings

#5631 USWDS - Button: Collapse unstyled button width at small viewport sizes
  packages/uswds-core/src/styles/mixins/general/button-unstyled.scss
Labels: Context: Sass, Package: Button, Role: A11Y

#5832 USWDS - Core: Remove unused dependencies
  package-lock.json
  package.json
Labels: Affects: Dependencies
